"""Add end time for inquiry times

Revision ID: 0d0eb75cb571
Revises: 760f0ceea92f
Create Date: 2021-09-24 23:01:02.492193

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0d0eb75cb571'
down_revision = '760f0ceea92f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inquiry_times', sa.Column('time_start', sa.Time(), nullable=True))
    op.add_column('inquiry_times', sa.Column('time_end', sa.Time(), nullable=True))
    op.drop_column('inquiry_times', 'time_start_minut')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inquiry_times', sa.Column('time_start_minut', postgresql.TIME(), autoincrement=False, nullable=True))
    op.drop_column('inquiry_times', 'time_end')
    op.drop_column('inquiry_times', 'time_start')
    # ### end Alembic commands ###
