"""added n:m relationships inquiries

Revision ID: 183f19d479bc
Revises: 0d0eb75cb571
Create Date: 2021-09-25 09:25:04.628651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '183f19d479bc'
down_revision = '0d0eb75cb571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inquiries_services',
    sa.Column('inquiry_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], )
    )
    op.create_table('inquiries_times',
    sa.Column('inquiry_id', sa.Integer(), nullable=True),
    sa.Column('time_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['inquiry_times.id'], )
    )
    op.drop_constraint('inquiries_time_id_fkey', 'inquiries', type_='foreignkey')
    op.drop_constraint('inquiries_service_id_fkey', 'inquiries', type_='foreignkey')
    op.drop_column('inquiries', 'time_id')
    op.drop_column('inquiries', 'service_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inquiries', sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('inquiries', sa.Column('time_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('inquiries_service_id_fkey', 'inquiries', 'services', ['service_id'], ['id'])
    op.create_foreign_key('inquiries_time_id_fkey', 'inquiries', 'inquiry_times', ['time_id'], ['id'])
    op.drop_table('inquiries_times')
    op.drop_table('inquiries_services')
    # ### end Alembic commands ###
