"""add foreignkey between times inquiries

Revision ID: 760f0ceea92f
Revises: 917092dc40b6
Create Date: 2021-09-24 22:05:51.240207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '760f0ceea92f'
down_revision = '917092dc40b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inquiries', sa.Column('time_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inquiries', 'inquiry_times', ['time_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inquiries', type_='foreignkey')
    op.drop_column('inquiries', 'time_id')
    # ### end Alembic commands ###
