"""add foreignkey between services inquiries

Revision ID: 917092dc40b6
Revises: b5752535378a
Create Date: 2021-09-24 22:02:42.247543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '917092dc40b6'
down_revision = 'b5752535378a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inquiries', sa.Column('service_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inquiries', 'services', ['service_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inquiries', type_='foreignkey')
    op.drop_column('inquiries', 'service_id')
    # ### end Alembic commands ###
