"""added status column

Revision ID: 99c9ac55e987
Revises: 183f19d479bc
Create Date: 2021-09-25 17:11:23.690961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99c9ac55e987'
down_revision = '183f19d479bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inquiries', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inquiries', 'status')
    # ### end Alembic commands ###
